spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/schoolManage
  jpa:
    show-sql: true


logging:
  level:
    root: info
    org.springframework.jdbc: debug
    com.example.bb.redisdataaccessdemo.dao: debug
